<script lang="ts">
    import "../app.css";
    import { page } from "$app/stores";
    import { onMount } from "svelte";

    // export let data;
    onMount(() => {
        console.log($page);
    });
</script>

<!-- <svelte:head> -->
<!--     <title>{$page.data.title ?? "imre.al"}</title> -->
<!-- </svelte:head> -->

<div id="preamble">
    <a href="/">
        <img src="/logo.png" alt="logo" />
    </a>
</div>

<slot />

<div id="postamble">
    <!-- <p>Generated by Org mode 9.6.6 in GNU Emacs 30.0.50</p> -->
</div>

<style>
    #preamble {
        margin-top: 5%;
        padding-bottom: 2%;
        display: inline-block;
        min-width: 20%;
        border-bottom: 2px solid #161616;
    }

    #postamble {
        display: inline-block;
        min-width: 20%;
        border-bottom: 2px solid #161616;
    }

    #content img {
        max-width: 100%;
        height: auto;
    }
</style>
