<script lang="ts">
    import "../app.css";
    import { page } from "$app/stores";
    import { onMount } from "svelte";

    export const prerender = true;
    // export const trailingSlash = 'always';

    export let data;

    onMount(() => {
        console.log($page);
    });
</script>

<svelte:head>
    <title>{$page.data.title ?? "imre.al"}</title>
</svelte:head>

<div id="preamble">
    <a href="/">
        <img src="/logo.png" alt="logo" />
    </a>
</div>

<slot />

<div id="postamble">
    <p>Generated by Org mode 9.6.6 in GNU Emacs 30.0.50</p>
</div>

<style>
    #preamble {
        margin-top: 5%;
        display: inline-block;
        border-bottom: 2px solid #161616;
    }

    #postamble {
        display: inline-block;
        border-bottom: 2px solid #161616;
    }

    #content img {
        max-width: 100%;
        height: auto;
    }
</style>
