<script lang="ts">
</script>

<div id="preamble">
    <a href="/">
        <img src="/logo.png" alt="logo" />
    </a>
</div>

<div id="content">
    <h1>test</h1>
    <ul>
        <li>
            <a href="contact.html">Contact</a>
        </li>
    </ul>
</div>


<div id="postamble">
    <p>Generated by Org mode 9.6.6 in GNU Emacs 30.0.50</p>
</div>

<style>
    #preamble {
        margin-top: 5%;
        display: inline-block;
        border-bottom: 2px solid #161616;
    }

    #postamble {
        display: inline-block;
        border-bottom: 2px solid #161616;
    }

    #content img {
        max-width: 100%;
        height: auto;
    }
</style>
